// <auto-generated />
using System;
using AniTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AniTrack.Data.Migrations
{
    [DbContext(typeof(AniTrackDbContext))]
    [Migration("20250805222605_AnimeReviewWithoutSeedingAdded")]
    partial class AnimeReviewWithoutSeedingAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AniTrack.Data.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Unique identifier for the anime series");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AirDate")
                        .HasColumnType("date")
                        .HasComment("The date when the anime series first aired");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasComment("The date when the anime series ended, if ended");

                    b.Property<int>("Episodes")
                        .HasColumnType("int")
                        .HasComment("Number of episodes of the anime series");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2083)
                        .HasColumnType("nvarchar(2083)")
                        .HasComment("URL of the anime series poster");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether the anime series is deleted");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Synopsis or description of the anime series");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasComment("Title of the anime series");

                    b.HasKey("Id");

                    b.ToTable("Animes", t =>
                        {
                            t.HasComment("Anime series in the system");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirDate = new DateOnly(2023, 9, 29),
                            EndDate = new DateOnly(2024, 3, 22),
                            Episodes = 28,
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/1015/138006.jpg",
                            IsDeleted = false,
                            Synopsis = "During their decade-long quest to defeat the Demon King, the members of the hero's party—Himmel himself, the priest Heiter, the dwarf warrior Eisen, and the elven mage Frieren—forge bonds through adventures and battles, creating unforgettable precious memories for most of them.\r\n\r\nHowever, the time that Frieren spends with her comrades is equivalent to merely a fraction of her life, which has lasted over a thousand years. When the party disbands after their victory, Frieren casually returns to her \"usual\" routine of collecting spells across the continent. Due to her different sense of time, she seemingly holds no strong feelings toward the experiences she went through.\r\n\r\nAs the years pass, Frieren gradually realizes how her days in the hero's party truly impacted her. Witnessing the deaths of two of her former companions, Frieren begins to regret having taken their presence for granted; she vows to better understand humans and create real personal connections. Although the story of that once memorable journey has long ended, a new tale is about to begin.",
                            Title = "Sousou no Frieren"
                        },
                        new
                        {
                            Id = 2,
                            AirDate = new DateOnly(2009, 4, 5),
                            EndDate = new DateOnly(2010, 7, 4),
                            Episodes = 64,
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/1223/96541.jpg",
                            IsDeleted = false,
                            Synopsis = "After a horrific alchemy experiment goes wrong in the Elric household, brothers Edward and Alphonse are left in a catastrophic new reality. Ignoring the alchemical principle banning human transmutation, the boys attempted to bring their recently deceased mother back to life. Instead, they suffered brutal personal loss: Alphonse's body disintegrated while Edward lost a leg and then sacrificed an arm to keep Alphonse's soul in the physical realm by binding it to a hulking suit of armor.\r\n\r\nThe brothers are rescued by their neighbor Pinako Rockbell and her granddaughter Winry. Known as a bio-mechanical engineering prodigy, Winry creates prosthetic limbs for Edward by utilizing \"automail,\" a tough, versatile metal used in robots and combat armor. After years of training, the Elric brothers set off on a quest to restore their bodies by locating the Philosopher's Stone—a powerful gem that allows an alchemist to defy the traditional laws of Equivalent Exchange.\r\n\r\nAs Edward becomes an infamous alchemist and gains the nickname \"Fullmetal,\" the boys' journey embroils them in a growing conspiracy that threatens the fate of the world.",
                            Title = "Fullmetal Alchemist: Brotherhood"
                        },
                        new
                        {
                            Id = 3,
                            AirDate = new DateOnly(2011, 4, 6),
                            EndDate = new DateOnly(2011, 9, 14),
                            Episodes = 24,
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/5/73199.jpg",
                            IsDeleted = false,
                            Synopsis = "Eccentric scientist Rintarou Okabe has a never-ending thirst for scientific exploration. Together with his ditzy but well-meaning friend Mayuri Shiina and his roommate Itaru Hashida, Okabe founds the Future Gadget Laboratory in the hopes of creating technological innovations that baffle the human psyche. Despite claims of grandeur, the only notable \"gadget\" the trio have created is a microwave that has the mystifying power to turn bananas into green goo.\r\n\r\nHowever, when Okabe attends a conference on time travel, he experiences a series of strange events that lead him to believe that there is more to the \"Phone Microwave\" gadget than meets the eye. Apparently able to send text messages into the past using the microwave, Okabe dabbles further with the \"time machine,\" attracting the ire and attention of the mysterious organization SERN.\r\n\r\nDue to the novel discovery, Okabe and his friends find themselves in an ever-present danger. As he works to mitigate the damage his invention has caused to the timeline, Okabe fights a battle to not only save his loved ones but also to preserve his degrading sanity.",
                            Title = "Steins;Gate"
                        },
                        new
                        {
                            Id = 4,
                            AirDate = new DateOnly(2011, 10, 2),
                            EndDate = new DateOnly(2014, 9, 24),
                            Episodes = 148,
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/1337/99013.jpg",
                            IsDeleted = false,
                            Synopsis = "Hunters devote themselves to accomplishing hazardous tasks, all from traversing the world's uncharted territories to locating rare items and monsters. Before becoming a Hunter, one must pass the Hunter Examination—a high-risk selection process in which most applicants end up handicapped or worse, deceased.\r\n\r\nAmbitious participants who challenge the notorious exam carry their own reason. What drives 12-year-old Gon Freecss is finding Ging, his father and a Hunter himself. Believing that he will meet his father by becoming a Hunter, Gon takes the first step to walk the same path.\r\n\r\nDuring the Hunter Examination, Gon befriends the medical student Leorio Paladiknight, the vindictive Kurapika, and ex-assassin Killua Zoldyck. While their motives vastly differ from each other, they band together for a common goal and begin to venture into a perilous world.",
                            Title = "Hunter x Hunter (2011)"
                        },
                        new
                        {
                            Id = 5,
                            AirDate = new DateOnly(2013, 4, 7),
                            EndDate = new DateOnly(2013, 9, 29),
                            Episodes = 25,
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/10/47347.jpg",
                            IsDeleted = false,
                            Synopsis = "Centuries ago, mankind was slaughtered to near extinction by monstrous humanoid creatures called Titans, forcing humans to hide in fear behind enormous concentric walls. What makes these giants truly terrifying is that their taste for human flesh is not born out of hunger but what appears to be out of pleasure. To ensure their survival, the remnants of humanity began living within defensive barriers, resulting in one hundred years without a single titan encounter. However, that fragile calm is soon shattered when a colossal Titan manages to breach the supposedly impregnable outer wall, reigniting the fight for survival against the man-eating abominations.\r\n\r\nAfter witnessing a horrific personal loss at the hands of the invading creatures, Eren Yeager dedicates his life to their eradication by enlisting into the Survey Corps, an elite military unit that combats the merciless humanoids outside the protection of the walls. Eren, his adopted sister Mikasa Ackerman, and his childhood friend Armin Arlert join the brutal war against the Titans and race to discover a way of defeating them before the last walls are breached.",
                            Title = "Attack On Titan"
                        },
                        new
                        {
                            Id = 6,
                            AirDate = new DateOnly(2006, 10, 4),
                            EndDate = new DateOnly(2007, 6, 27),
                            Episodes = 37,
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/9/9453.jpg",
                            IsDeleted = false,
                            Synopsis = "Brutal murders, petty thefts, and senseless violence pollute the human world. In contrast, the realm of death gods is a humdrum, unchanging gambling den. The ingenious 17-year-old Japanese student Light Yagami and sadistic god of death Ryuk share one belief: their worlds are rotten.\r\n\r\nFor his own amusement, Ryuk drops his Death Note into the human world. Light stumbles upon it, deeming the first of its rules ridiculous: the human whose name is written in this note shall die. However, the temptation is too great, and Light experiments by writing a felon's name, which disturbingly enacts his first murder.\r\n\r\nAware of the terrifying godlike power that has fallen into his hands, Light—under the alias Kira—follows his wicked sense of justice with the ultimate goal of cleansing the world of all evil-doers. The meticulous mastermind detective L is already on his trail, but as Light's brilliance rivals L's, the grand chase for Kira turns into an intense battle of wits that can only end when one of them is dead.",
                            Title = "Death Note"
                        },
                        new
                        {
                            Id = 7,
                            AirDate = new DateOnly(2019, 4, 6),
                            EndDate = new DateOnly(2019, 9, 28),
                            Episodes = 26,
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/1286/99889.jpg",
                            IsDeleted = false,
                            Synopsis = "Ever since the death of his father, the burden of supporting the family has fallen upon Tanjirou Kamado's shoulders. Though living impoverished on a remote mountain, the Kamado family are able to enjoy a relatively peaceful and happy life. One day, Tanjirou decides to go down to the local village to make a little money selling charcoal. On his way back, night falls, forcing Tanjirou to take shelter in the house of a strange man, who warns him of the existence of flesh-eating demons that lurk in the woods at night.\r\n\r\nWhen he finally arrives back home the next day, he is met with a horrifying sight—his whole family has been slaughtered. Worse still, the sole survivor is his sister Nezuko, who has been turned into a bloodthirsty demon. Consumed by rage and hatred, Tanjirou swears to avenge his family and stay by his only remaining sibling. Alongside the mysterious group calling themselves the Demon Slayer Corps, Tanjirou will do whatever it takes to slay the demons and protect the remnants of his beloved sister's humanity.",
                            Title = "Demon Slayer"
                        },
                        new
                        {
                            Id = 8,
                            AirDate = new DateOnly(2020, 10, 3),
                            EndDate = new DateOnly(2021, 3, 27),
                            Episodes = 24,
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/1171/109222.jpg",
                            IsDeleted = false,
                            Synopsis = "Idly indulging in baseless paranormal activities with the Occult Club, high schooler Yuuji Itadori spends his days at either the clubroom or the hospital, where he visits his bedridden grandfather. However, this leisurely lifestyle soon takes a turn for the strange when he unknowingly encounters a cursed item. Triggering a chain of supernatural occurrences, Yuuji finds himself suddenly thrust into the world of Curses—dreadful beings formed from human malice and negativity—after swallowing the said item, revealed to be a finger belonging to the demon Sukuna Ryoumen, the King of Curses.\r\n\r\nYuuji experiences first-hand the threat these Curses pose to society as he discovers his own newfound powers. Introduced to the Tokyo Prefectural Jujutsu High School, he begins to walk down a path from which he cannot return—the path of a Jujutsu sorcerer.",
                            Title = "Jujutsu Kaisen"
                        },
                        new
                        {
                            Id = 9,
                            AirDate = new DateOnly(2016, 4, 3),
                            EndDate = new DateOnly(2016, 6, 26),
                            Episodes = 13,
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/10/78745.jpg",
                            IsDeleted = false,
                            Synopsis = "The appearance of \"quirks,\" newly discovered super powers, has been steadily increasing over the years, with 80 percent of humanity possessing various abilities from manipulation of elements to shapeshifting. This leaves the remainder of the world completely powerless, and Izuku Midoriya is one such individual.\r\n\r\nSince he was a child, the ambitious middle schooler has wanted nothing more than to be a hero. Izuku's unfair fate leaves him admiring heroes and taking notes on them whenever he can. But it seems that his persistence has borne some fruit: Izuku meets the number one hero and his personal idol, All Might. All Might's quirk is a unique ability that can be inherited, and he has chosen Izuku to be his successor!\r\n\r\nEnduring many months of grueling training, Izuku enrolls in UA High, a prestigious high school famous for its excellent hero training program, and this year's freshmen look especially promising. With his bizarre but talented classmates and the looming threat of a villainous organization, Izuku will soon learn what it really means to be a hero.",
                            Title = "My Hero Academia"
                        },
                        new
                        {
                            Id = 10,
                            AirDate = new DateOnly(2015, 10, 5),
                            EndDate = new DateOnly(2015, 12, 21),
                            Episodes = 12,
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/12/76049.jpg",
                            IsDeleted = false,
                            Synopsis = "The seemingly unimpressive Saitama has a rather unique hobby: being a hero. In order to pursue his childhood dream, Saitama relentlessly trained for three years, losing all of his hair in the process. Now, Saitama is so powerful, he can defeat any enemy with just one punch. However, having no one capable of matching his strength has led Saitama to an unexpected problem—he is no longer able to enjoy the thrill of battling and has become quite bored.\r\n\r\nOne day, Saitama catches the attention of 19-year-old cyborg Genos, who witnesses his power and wishes to become Saitama's disciple. Genos proposes that the two join the Hero Association in order to become certified heroes that will be recognized for their positive contributions to society. Saitama, who is shocked that no one knows who he is, quickly agrees. Meeting new allies and taking on new foes, Saitama embarks on a new journey as a member of the Hero Association to experience the excitement of battle he once felt.",
                            Title = "One Punch Man"
                        });
                });

            modelBuilder.Entity("AniTrack.Data.Models.AnimeGenre", b =>
                {
                    b.Property<int>("AnimeId")
                        .HasColumnType("int")
                        .HasComment("The unique identifier for the Anime associated with this Genre.");

                    b.Property<int>("GenreId")
                        .HasColumnType("int")
                        .HasComment("The unique identifier for the Genre associated with this Anime.");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether this AnimeGenre record is deleted (soft delete).");

                    b.HasKey("AnimeId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("AnimesGenres", t =>
                        {
                            t.HasComment("Represents the relationship between Anime and Genre in the AniTrack database.");
                        });

                    b.HasData(
                        new
                        {
                            AnimeId = 1,
                            GenreId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 1,
                            GenreId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 1,
                            GenreId = 8,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 2,
                            GenreId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 2,
                            GenreId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 2,
                            GenreId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 2,
                            GenreId = 8,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 3,
                            GenreId = 14,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 3,
                            GenreId = 18,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 3,
                            GenreId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 4,
                            GenreId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 4,
                            GenreId = 2,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 4,
                            GenreId = 8,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 5,
                            GenreId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 5,
                            GenreId = 7,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 5,
                            GenreId = 18,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 5,
                            GenreId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 6,
                            GenreId = 18,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 6,
                            GenreId = 17,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 7,
                            GenreId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 7,
                            GenreId = 17,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 7,
                            GenreId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 8,
                            GenreId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 8,
                            GenreId = 17,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 8,
                            GenreId = 4,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 9,
                            GenreId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 10,
                            GenreId = 1,
                            IsDeleted = false
                        },
                        new
                        {
                            AnimeId = 10,
                            GenreId = 6,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("AniTrack.Data.Models.AnimeReview", b =>
                {
                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Unique identifier for the review author");

                    b.Property<int>("AnimeId")
                        .HasColumnType("int")
                        .HasComment("Unique identifier for the anime being reviewed");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasComment("Content of the review");

                    b.Property<DateTime>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()")
                        .HasComment("The date when the review was created");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether the review is deleted");

                    b.Property<bool>("isAnimeRecommended")
                        .HasColumnType("bit")
                        .HasComment("Indicates whether the review recommends the anime");

                    b.HasKey("AuthorId", "AnimeId");

                    b.HasIndex("AnimeId");

                    b.ToTable("AnimeReviews");
                });

            modelBuilder.Entity("AniTrack.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AniTrack.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("The unique identifier for the Genre.");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether this Genre record is deleted (soft delete).");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("The name of the Genre.");

                    b.HasKey("Id");

                    b.ToTable("Genres", t =>
                        {
                            t.HasComment("Represents a Genre in the AniTrack database.");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Avant Garde"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Award Winning"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            Name = "Boys Love"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            Name = "Girls Love"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            Name = "Gourmet"
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            Name = "Mystery"
                        },
                        new
                        {
                            Id = 13,
                            IsDeleted = false,
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 14,
                            IsDeleted = false,
                            Name = "Sci-Fi"
                        },
                        new
                        {
                            Id = 15,
                            IsDeleted = false,
                            Name = "Slice of Life"
                        },
                        new
                        {
                            Id = 16,
                            IsDeleted = false,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 17,
                            IsDeleted = false,
                            Name = "Supernatural"
                        },
                        new
                        {
                            Id = 18,
                            IsDeleted = false,
                            Name = "Suspense"
                        });
                });

            modelBuilder.Entity("AniTrack.Data.Models.UserAnime", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasComment("Foreign Key reference to AspNetUser");

                    b.Property<int>("AnimeId")
                        .HasColumnType("int")
                        .HasComment("Foreign Key reference to Anime");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasComment("Indicates whether this UserAnime record is deleted (soft delete).");

                    b.HasKey("UserId", "AnimeId");

                    b.HasIndex("AnimeId");

                    b.ToTable("UsersAnimes", t =>
                        {
                            t.HasComment("Represents User Watchlist relation in database");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AniTrack.Data.Models.AnimeGenre", b =>
                {
                    b.HasOne("AniTrack.Data.Models.Anime", "Anime")
                        .WithMany("AnimeGenres")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniTrack.Data.Models.Genre", "Genre")
                        .WithMany("AnimesGenre")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("AniTrack.Data.Models.AnimeReview", b =>
                {
                    b.HasOne("AniTrack.Data.Models.Anime", "Anime")
                        .WithMany("Reviews")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AniTrack.Data.Models.ApplicationUser", "Author")
                        .WithMany("Reviews")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("AniTrack.Data.Models.UserAnime", b =>
                {
                    b.HasOne("AniTrack.Data.Models.Anime", "Anime")
                        .WithMany("UserWatchlists")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AniTrack.Data.Models.ApplicationUser", "User")
                        .WithMany("Animelist")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AniTrack.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AniTrack.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AniTrack.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AniTrack.Data.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AniTrack.Data.Models.Anime", b =>
                {
                    b.Navigation("AnimeGenres");

                    b.Navigation("Reviews");

                    b.Navigation("UserWatchlists");
                });

            modelBuilder.Entity("AniTrack.Data.Models.ApplicationUser", b =>
                {
                    b.Navigation("Animelist");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("AniTrack.Data.Models.Genre", b =>
                {
                    b.Navigation("AnimesGenre");
                });
#pragma warning restore 612, 618
        }
    }
}
